import { Geist, Geist_Mono } from "next/font/google";

import { AuthProvider } from "@/contexts/authContext";
import Wrapper from "@/components/commons/layout/Wrapper";
import LayoutHeader from "@/components/commons/layout/LayoutHeader";

import type { Metadata } from "next";
import "./globals.css";
// import MobileMenu from "@/components/commons/layout/mobileMenu";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AuthProvider>
          <LayoutHeader />
          {/* <main className="h-[calc(100%-3rem)]">{children}</main> */}
          <main className="h-full">
            <Wrapper>{children}</Wrapper>
          </main>
          {/* <div className="block sm:hidden">
          <MobileMenu />
        </div> */}
        </AuthProvider>
      </body>
    </html>
  );
}
