import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import LayoutHeader from "@/components/commons/layout/LayoutHeader";
import MobileMenu from "@/components/commons/layout/MobileMenu";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <LayoutHeader />
        <main className="h-[calc(100%-3rem)]">{children}</main>
        <div className="block sm:hidden">
          <MobileMenu />
        </div>
      </body>
    </html>
  );
}
